version: '2'
services:
  uber-workflow-probot:
    build: .
    volumes:
      - .:/uber-workflow-probot
      - /uber-workflow-probot/node_modules/
    environment:
      - NOW_TOKEN
      - NOW_TEAM
      - BUILDKITE
      - BUILDKITE_REPO
      - BUILDKITE_BRANCH
      - BUILDKITE_PULL_REQUEST
